# Generated by Django 5.1 on 2026-08-25 06:27

import apps.orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tag_product_is_bestseller_product_is_featured_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_label_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Order Confirmed'), ('PACKED', 'Packed in Warehouse'), ('PROCESSING', 'Processing Fulfillment'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('PENDING', 'Pending Fulfillment'), ('PACKED', 'Packed'), ('SHIPPED', 'Item Shipped'), ('DELIVERED', 'Item Delivered'), ('CANCELLED', 'Item Cancelled'), ('RETURNED', 'Item Returned')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('LABEL_CREATED', 'Shipping Label Created'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Package Delivered'), ('FAILED_ATTEMPT', 'Delivery Attempt Failed')], default='LABEL_CREATED', max_length=30),
        ),
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.CharField(default=apps.orders.models.generate_exc_id, max_length=64, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Exchange Completed')], default='SUBMITTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='orders.orderitem')),
                ('target_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_exchanges', to='catalog.productvariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.CharField(default=apps.orders.models.generate_osh_id, max_length=64, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.CharField(default=apps.orders.models.generate_sev_id, max_length=64, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=150)),
                ('status_description', models.CharField(max_length=255)),
                ('event_timestamp', models.DateTimeField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.shipment')),
            ],
            options={
                'ordering': ['-event_timestamp'],
            },
        ),
    ]
