# Generated by Django 6.1 on 2026-09-04 16:57

import apps.orders.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_speed',
            field=models.CharField(default='STANDARD', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_wrap_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_wrap_type',
            field=models.CharField(default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('id', models.CharField(default=apps.orders.models.generate_inv_id, max_length=64, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('tax_identifier', models.CharField(default='US-EIN-94-3829101', max_length=50)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order')),
            ],
        ),
    ]
