const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED_ACCESS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN_ACTION',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  COUPON_INVALID: 'COUPON_INVALID_OR_EXPIRED',
  PAYMENT_FAILED: 'PAYMENT_PROCESSING_FAILED',
  INTERNAL_ERROR: 'INTERNAL_SERVER_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED'
};

module.exports = ERROR_CODES;
