# Generated by Django 5.1 on 2026-08-25 06:27

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='language',
            field=models.CharField(default='en-us', max_length=10),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.generate_reset_id, max_length=64, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.generate_paymeth_id, max_length=64, primary_key=True, serialize=False)),
                ('card_brand', models.CharField(default='Visa', max_length=50)),
                ('last4', models.CharField(max_length=4)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('gateway_token_ref', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
