# Generated by Django 5.1 on 2026-08-25 05:58

import apps.sellers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.CharField(default=apps.sellers.models.generate_seller_id, max_length=64, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=8.5, max_digits=5)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=4.8, max_digits=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved Merchant'), ('SUSPENDED', 'Suspended')], default='APPROVED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
