# Generated by Django 5.1 on 2026-08-25 06:27

import apps.sellers.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.85'), max_digits=3),
        ),
        migrations.CreateModel(
            name='SellerOnboarding',
            fields=[
                ('id', models.CharField(default=apps.sellers.models.generate_onboarding_id, max_length=64, primary_key=True, serialize=False)),
                ('is_identity_verified', models.BooleanField(default=False)),
                ('is_bank_verified', models.BooleanField(default=False)),
                ('is_tax_verified', models.BooleanField(default=False)),
                ('current_step', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerSettlement',
            fields=[
                ('id', models.CharField(default=apps.sellers.models.generate_settlement_id, max_length=64, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('gross_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSED', 'Payout Settled'), ('ON_HOLD', 'On Hold')], default='PENDING', max_length=30)),
                ('payout_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='sellers.seller')),
            ],
        ),
    ]
