# Generated by Django 5.1 on 2026-08-25 06:27

import apps.cart.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0002_tag_product_is_bestseller_product_is_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCart',
            fields=[
                ('id', models.CharField(default=apps.cart.models.generate_scrt_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Saved Cart', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedCartItem',
            fields=[
                ('id', models.CharField(default=apps.cart.models.generate_scitem_id, max_length=64, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('saved_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.savedcart')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cart_entries', to='catalog.productvariant')),
            ],
            options={
                'unique_together': {('saved_cart', 'variant')},
            },
        ),
    ]
