# Generated by Django 5.1 on 2026-08-25 05:58

import apps.returns.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.CharField(default=apps.returns.models.generate_ret_id, max_length=64, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Return Request Submitted'), ('APPROVED', 'Return Approved'), ('REJECTED', 'Return Rejected'), ('REFUNDED', 'Refund Processed')], default='SUBMITTED', max_length=30)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
