# Generated by Django 5.1 on 2026-08-25 06:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='restocking_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='return_shipping_label_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('DEFECTIVE', 'Item Defective or Malfunctioning'), ('WRONG_ITEM', 'Wrong Item Delivered'), ('DAMAGED_IN_SHIPPING', 'Damaged During Transit'), ('CHANGED_MIND', 'Buyer Changed Mind')], default='DEFECTIVE', max_length=50),
        ),
    ]
