# Generated by Django 6.1 on 2026-09-12 04:36

import apps.payouts.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_lightningdeal_lightningdealclaim_productanswervote_and_more'),
        ('orders', '0003_order_delivery_speed_order_gift_message_and_more'),
        ('sellers', '0002_alter_seller_rating_avg_selleronboarding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.CharField(default=apps.payouts.models.generate_pyb_id, max_length=64, primary_key=True, serialize=False)),
                ('batch_reference', models.CharField(max_length=50, unique=True)),
                ('cycle_start', models.DateField()),
                ('cycle_end', models.DateField()),
                ('total_sellers_count', models.PositiveIntegerField(default=0)),
                ('total_gross_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_commission_retained', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_net_disbursed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Calculation'), ('APPROVED', 'Approved for Settlement'), ('PROCESSING', 'Processing with Clearinghouse'), ('COMPLETED', 'Disbursed to Sellers'), ('FAILED', 'Disbursement Failed')], default='DRAFT', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerBankAccount',
            fields=[
                ('id', models.CharField(default=apps.payouts.models.generate_bnk_id, max_length=64, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('routing_number', models.CharField(max_length=50)),
                ('account_number_last4', models.CharField(max_length=4)),
                ('account_type', models.CharField(default='CHECKING', max_length=20)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutItem',
            fields=[
                ('id', models.CharField(default=apps.payouts.models.generate_pyi_id, max_length=64, primary_key=True, serialize=False)),
                ('gross_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_settled', models.BooleanField(default=False)),
                ('transfer_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payouts.payoutbatch')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_items', to='sellers.seller')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payouts.sellerbankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SellerCommissionRule',
            fields=[
                ('id', models.CharField(default=apps.payouts.models.generate_cmr_id, max_length=64, primary_key=True, serialize=False)),
                ('tier_name', models.CharField(default='Standard Category Fee', max_length=50)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('minimum_fee', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='SellerEscrowAccount',
            fields=[
                ('id', models.CharField(default=apps.payouts.models.generate_esc_id, max_length=64, primary_key=True, serialize=False)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('withheld_disputed_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('lifetime_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('lifetime_payouts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_payout_hold', models.BooleanField(default=False)),
                ('hold_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_account', to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.CharField(default=apps.payouts.models.generate_etx_id, max_length=64, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('ORDER_HOLD', 'Order Payment Held in Escrow'), ('RETURN_WINDOW_RELEASE', 'Released to Available Balance'), ('RETURN_CLAWBACK', 'Refund Deduction for Customer Return'), ('DISPUTE_HOLD', 'Hold for Chargeback / Dispute'), ('COMMISSION_DEDUCTION', 'Marketplace Referral Fee Deduction'), ('PAYOUT_SETTLEMENT', 'Transfer Out via Payout Batch')], max_length=30)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_eligible_at', models.DateTimeField(blank=True, null=True)),
                ('is_released', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_transactions', to='orders.order')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payouts.sellerescrowaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
