# Generated by Django 5.1 on 2026-08-25 05:58

import apps.promotions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.CharField(default=apps.promotions.models.generate_cpn_id, max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount (%)'), ('FIXED', 'Fixed Amount Discount ($)')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usage_limit', models.IntegerField(default=1000)),
                ('per_user_limit', models.IntegerField(default=1)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionalCampaign',
            fields=[
                ('id', models.CharField(default=apps.promotions.models.generate_cmp_id, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('banner_url', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
