# Generated by Django 6.1 on 2026-09-12 04:36

import apps.logistics.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_delivery_speed_order_gift_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.CharField(default=apps.logistics.models.generate_car_id, max_length=64, primary_key=True, serialize=False)),
                ('carrier_code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('carrier_type', models.CharField(choices=[('EXPRESS', 'Express Air'), ('GROUND', 'Standard Ground'), ('FREIGHT', 'Heavy Freight'), ('LOCAL', 'Same-Day Courier')], default='GROUND', max_length=20)),
                ('tracking_url_template', models.CharField(default='https://track.shopsphere.internal/?id={tracking_number}', max_length=255)),
                ('base_rate_per_kg', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=8)),
                ('minimum_fee', models.DecimalField(decimal_places=2, default=Decimal('4.99'), max_digits=8)),
                ('standard_sla_days', models.PositiveIntegerField(default=3)),
                ('supports_prime_expedited', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseHub',
            fields=[
                ('id', models.CharField(default=apps.logistics.models.generate_whb_id, max_length=64, primary_key=True, serialize=False)),
                ('hub_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='US', max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, default=Decimal('37.774900'), max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=Decimal('-122.419400'), max_digits=9)),
                ('capacity_sqft', models.PositiveIntegerField(default=100000)),
                ('current_utilization_pct', models.DecimalField(decimal_places=2, default=Decimal('65.00'), max_digits=5)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentParcel',
            fields=[
                ('id', models.CharField(default=apps.logistics.models.generate_pcl_id, max_length=64, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('packing_slip_number', models.CharField(max_length=50, unique=True)),
                ('length_cm', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=6)),
                ('width_cm', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=6)),
                ('height_cm', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=6)),
                ('actual_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('1.20'), max_digits=6)),
                ('volumetric_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('1.80'), max_digits=6)),
                ('shipping_fee_charged', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('status', models.CharField(choices=[('LABEL_CREATED', 'Shipping Label Generated'), ('PACKED', 'Packed in Facility'), ('DISPATCHED', 'Dispatched from Hub'), ('IN_TRANSIT', 'In Transit Between Hubs'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered to Recipient'), ('EXCEPTION', 'Delivery Exception / Delayed'), ('RETURNED_TO_ORIGIN', 'Returned to Origin (RTO)')], default='LABEL_CREATED', max_length=30)),
                ('current_location_desc', models.CharField(default='Origin Fulfillment Center', max_length=150)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_address_line', models.CharField(max_length=255)),
                ('recipient_city', models.CharField(max_length=100)),
                ('recipient_state', models.CharField(max_length=50)),
                ('recipient_postal_code', models.CharField(max_length=20)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='logistics.carrier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_parcels', to='orders.order')),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_parcels', to='logistics.warehousehub')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingCheckpoint',
            fields=[
                ('id', models.CharField(default=apps.logistics.models.generate_tcp_id, max_length=64, primary_key=True, serialize=False)),
                ('milestone_name', models.CharField(max_length=100)),
                ('facility_name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(default='US', max_length=10)),
                ('status_code', models.CharField(max_length=30)),
                ('checkpoint_notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='logistics.shipmentparcel')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentZone',
            fields=[
                ('id', models.CharField(default=apps.logistics.models.generate_fzn_id, max_length=64, primary_key=True, serialize=False)),
                ('zone_code', models.CharField(max_length=30, unique=True)),
                ('postal_prefix', models.CharField(db_index=True, max_length=10)),
                ('state_code', models.CharField(max_length=10)),
                ('sla_transit_hours', models.PositiveIntegerField(default=48)),
                ('express_eligible', models.BooleanField(default=True)),
                ('primary_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_zones', to='logistics.warehousehub')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchManifest',
            fields=[
                ('id', models.CharField(default=apps.logistics.models.generate_mnf_id, max_length=64, primary_key=True, serialize=False)),
                ('manifest_number', models.CharField(max_length=50, unique=True)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('vehicle_registration', models.CharField(blank=True, max_length=50)),
                ('total_packages', models.PositiveIntegerField(default=0)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifests', to='logistics.carrier')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='logistics.warehousehub')),
            ],
        ),
    ]
