# Generated by Django 6.1 on 2026-09-12 04:36

import apps.recommendations.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_lightningdeal_lightningdealclaim_productanswervote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyBoughtTogether',
            fields=[
                ('id', models.CharField(default=apps.recommendations.models.generate_fbt_id, max_length=64, primary_key=True, serialize=False)),
                ('bundle_discount_pct', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('co_occurrence_count', models.PositiveIntegerField(default=42)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frequently_bought_bundle', to='catalog.product')),
                ('bundle_item_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbt_bundle_1', to='catalog.product')),
                ('bundle_item_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fbt_bundle_2', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSimilarity',
            fields=[
                ('id', models.CharField(default=apps.recommendations.models.generate_sim_id, max_length=64, primary_key=True, serialize=False)),
                ('similarity_score', models.DecimalField(decimal_places=4, default=Decimal('0.8500'), max_digits=5)),
                ('match_type', models.CharField(choices=[('CONTENT_SPECS', 'Attribute & Specifications Match'), ('CO_PURCHASE', 'Marketplace Co-Purchase Frequency'), ('CATEGORY_HYBRID', 'Hierarchical Category Nearest Neighbor')], default='CONTENT_SPECS', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_from', to='catalog.product')),
                ('target_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_to', to='catalog.product')),
            ],
            options={
                'ordering': ['-similarity_score'],
                'unique_together': {('source_product', 'target_product', 'match_type')},
            },
        ),
        migrations.CreateModel(
            name='UserCategoryAffinity',
            fields=[
                ('id', models.CharField(default=apps.recommendations.models.generate_aff_id, max_length=64, primary_key=True, serialize=False)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('affinity_score', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_affinities', to='catalog.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_affinities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-affinity_score'],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
