# Generated by Django 5.1 on 2026-08-25 05:58

import apps.payments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=apps.payments.models.generate_pay_id, max_length=64, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(default='CREDIT_CARD_SANDBOX', max_length=50)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Payment Approved'), ('FAILED', 'Payment Declined'), ('REFUNDED', 'Payment Refunded')], default='SUCCESS', max_length=30)),
                ('gateway_response_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
        ),
    ]
