# Generated by Django 5.1 on 2026-08-25 06:27

import apps.payments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_estimated_delivery_date_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Payment Pending'), ('AUTHORIZED', 'Payment Authorized'), ('CAPTURED', 'Payment Captured'), ('SUCCESS', 'Payment Approved'), ('FAILED', 'Payment Declined'), ('REFUNDED', 'Payment Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='SUCCESS', max_length=30),
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.CharField(default=apps.payments.models.generate_int_id, max_length=64, primary_key=True, serialize=False)),
                ('intent_token', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('CREATED', 'Intent Created'), ('REQUIRES_PAYMENT_METHOD', 'Requires Payment Method'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLedger',
            fields=[
                ('id', models.CharField(default=apps.payments.models.generate_led_id, max_length=64, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('AUTHORIZATION', 'Payment Authorization'), ('CAPTURE', 'Payment Capture'), ('REFUND', 'Refund Processing'), ('COMMISSION_FEE', 'Platform Commission Fee')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='payments.payment')),
            ],
        ),
    ]
