# Generated by Django 6.1 on 2026-09-12 04:36

import apps.memberships.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_lightningdeal_lightningdealclaim_productanswervote_and_more'),
        ('orders', '0003_order_delivery_speed_order_gift_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.CharField(default=apps.memberships.models.generate_mtr_id, max_length=64, primary_key=True, serialize=False)),
                ('tier_code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(default='Fast, free delivery and exclusive member benefits', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('14.99'), max_digits=8)),
                ('billing_period_days', models.PositiveIntegerField(default=30)),
                ('free_shipping_min_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('cashback_reward_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('has_early_deal_access', models.BooleanField(default=True)),
                ('has_free_same_day', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardWallet',
            fields=[
                ('id', models.CharField(default=apps.memberships.models.generate_wal_id, max_length=64, primary_key=True, serialize=False)),
                ('points_balance', models.PositiveIntegerField(default=0)),
                ('lifetime_points_earned', models.PositiveIntegerField(default=0)),
                ('lifetime_points_redeemed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.CharField(default=apps.memberships.models.generate_rtx_id, max_length=64, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('PURCHASE_EARN', 'Points Earned on Purchase'), ('PRIME_BONUS', 'Prime Member Bonus Multiplier'), ('CHECKOUT_REDEEM', 'Points Redeemed at Checkout'), ('PROMO_GIFT', 'Special Promotional Credit'), ('REFUND_REVERSAL', 'Points Clawed Back for Return')], max_length=30)),
                ('points', models.IntegerField()),
                ('cash_equivalent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance_after', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_transactions', to='orders.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='memberships.rewardwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.CharField(default=apps.memberships.models.generate_sub_id, max_length=64, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('frequency_months', models.PositiveIntegerField(choices=[(1, 'Every 1 Month (5% Discount)'), (2, 'Every 2 Months (10% Discount)'), (3, 'Every 3 Months (10% Discount)'), (6, 'Every 6 Months (15% Discount)')], default=1)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Auto-Delivery'), ('PAUSED', 'Paused by Customer'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('next_delivery_date', models.DateField()),
                ('shipping_address_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_subscriptions', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionExecutionLog',
            fields=[
                ('id', models.CharField(default=apps.memberships.models.generate_sxl_id, max_length=64, primary_key=True, serialize=False)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SUCCESS', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='memberships.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.CharField(default=apps.memberships.models.generate_ums_id, max_length=64, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Member'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled by User'), ('PAYMENT_FAILED', 'Payment Renewal Failed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_members', to='memberships.membershiptier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
