# Generated by Django 5.1 on 2026-08-25 06:27

import apps.inventory.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tag_product_is_bestseller_product_is_featured_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quantity_damaged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouselocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('RECEIPT', 'Inventory Receipt / Restock'), ('DEDUCTION', 'Order Deduction'), ('RESERVATION', 'Checkout Reservation'), ('RELEASE', 'Reservation Release'), ('RETURN', 'RMA Return Credit'), ('DAMAGE_ADJUSTMENT', 'Damaged Stock Adjustment')], max_length=30),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.CharField(default=apps.inventory.models.generate_po_id, max_length=64, primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('supplier_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft PO'), ('SUBMITTED', 'Submitted to Supplier'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Fully Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.warehouselocation')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.CharField(default=apps.inventory.models.generate_poi_id, max_length=64, primary_key=True, serialize=False)),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_received', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='catalog.productvariant')),
            ],
        ),
    ]
