# Generated by Django 6.1 on 2026-09-04 16:57

import apps.support.knowledgebase
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket_assigned_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.CharField(default=apps.support.knowledgebase.generate_faqcat_id, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon_name', models.CharField(default='help-circle', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FAQArticle',
            fields=[
                ('id', models.CharField(default=apps.support.knowledgebase.generate_faqart_id, max_length=64, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('helpful_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='support.faqcategory')),
            ],
            options={
                'ordering': ['-helpful_count', '-created_at'],
            },
        ),
    ]
