# Generated by Django 5.1 on 2026-08-25 06:27

import apps.audit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.CharField(default=apps.audit.models.generate_flg_id, max_length=64, primary_key=True, serialize=False)),
                ('flag_key', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityThreatIP',
            fields=[
                ('id', models.CharField(default=apps.audit.models.generate_thr_id, max_length=64, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(max_length=200)),
                ('threat_level', models.CharField(default='MEDIUM', max_length=20)),
                ('is_blocked', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
