# Generated by Django 5.1 on 2026-08-25 06:27

import apps.analytics.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('catalog', '0002_tag_product_is_bestseller_product_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDailyMetric',
            fields=[
                ('id', models.CharField(default=apps.analytics.models.generate_pdm_id, max_length=64, primary_key=True, serialize=False)),
                ('metric_date', models.DateField(unique=True)),
                ('gross_merchandise_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('order_count', models.IntegerField(default=0)),
                ('active_customers', models.IntegerField(default=0)),
                ('active_sellers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.CharField(default=apps.analytics.models.generate_prm_id, max_length=64, primary_key=True, serialize=False)),
                ('total_views', models.IntegerField(default=0)),
                ('total_cart_additions', models.IntegerField(default=0)),
                ('total_units_sold', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='catalog.product')),
            ],
        ),
    ]
