# Generated by Django 5.1 on 2026-08-25 06:27

import apps.catalog.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(default=apps.catalog.models.generate_tag_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductModerationLog',
            fields=[
                ('id', models.CharField(default=apps.catalog.models.generate_mod_id, max_length=64, primary_key=True, serialize=False)),
                ('status_from', models.CharField(max_length=30)),
                ('status_to', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_moderations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.CharField(default=apps.catalog.models.generate_qna_id, max_length=64, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAnswer',
            fields=[
                ('id', models.CharField(default=apps.catalog.models.generate_ans_id, max_length=64, primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('is_seller_answer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='catalog.productquestion')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.tag'),
        ),
        migrations.CreateModel(
            name='ProductRelationship',
            fields=[
                ('id', models.CharField(default=apps.catalog.models.generate_rel_id, max_length=64, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('BOUGHT_TOGETHER', 'Frequently Bought Together'), ('RELATED', 'Related Product'), ('SIMILAR', 'Similar Product'), ('UPSELL', 'Upgrade Upsell')], default='RELATED', max_length=30)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.85'), max_digits=5)),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relationships', to='catalog.product')),
                ('target_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relationships', to='catalog.product')),
            ],
            options={
                'unique_together': {('source_product', 'target_product', 'relationship_type')},
            },
        ),
    ]
