# Generated by Django 5.1 on 2026-08-25 06:27

import apps.reviews.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.CharField(default=apps.reviews.models.generate_rep_id, max_length=64, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_review_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
