# Generated by Django 5.1 on 2026-08-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER', 'Order Updates'), ('SHIPMENT', 'Shipment Tracking'), ('RETURN', 'RMA Return Status'), ('SELLER', 'Seller Merchant Notification'), ('PROMOTION', 'Promotional Campaign'), ('PRICE_DROP', 'Price Drop Alert'), ('STOCK_ALERT', 'Back in Stock Alert'), ('SUPPORT', 'Support Ticket Reply'), ('SYSTEM', 'System Security Alert')], default='ORDER', max_length=30),
        ),
    ]
