# Generated by Django 6.1 on 2026-09-12 04:36

import apps.chat.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_delivery_speed_order_gift_message_and_more'),
        ('sellers', '0002_alter_seller_rating_avg_selleronboarding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotKnowledgeRule',
            fields=[
                ('id', models.CharField(default=apps.chat.models.generate_bkr_id, max_length=64, primary_key=True, serialize=False)),
                ('intent_tag', models.CharField(max_length=50, unique=True)),
                ('keyword_triggers', models.CharField(help_text='Comma-separated trigger keywords', max_length=255)),
                ('automated_response', models.TextField()),
                ('should_escalate_to_human', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('id', models.CharField(default=apps.chat.models.generate_chn_id, max_length=64, primary_key=True, serialize=False)),
                ('channel_code', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('channel_type', models.CharField(choices=[('SUPPORT_TRIAGE', '24/7 Automated Support & Helpdesk'), ('SELLER_INQUIRY', 'Customer to Seller Direct Inquiry'), ('ORDER_DISPUTE', 'Order Fulfillment Dispute')], default='SUPPORT_TRIAGE', max_length=30)),
                ('subject', models.CharField(default='Order & General Marketplace Assistance', max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'Active Open Channel'), ('WAITING_ON_AGENT', 'Queued for Human Support Specialist'), ('WAITING_ON_CUSTOMER', 'Waiting for Customer Reply'), ('RESOLVED', 'Issue Resolved'), ('CLOSED', 'Channel Closed')], default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_chats', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_channels', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to='orders.order')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_inquiries', to='sellers.seller')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(default=apps.chat.models.generate_msg_id, max_length=64, primary_key=True, serialize=False)),
                ('sender_role', models.CharField(choices=[('CUSTOMER', 'Shopper / Buyer'), ('SELLER', 'Merchant Partner'), ('SUPPORT_AGENT', 'Human Support Specialist'), ('AI_BOT', 'ShopSphere Automated Virtual Assistant')], default='CUSTOMER', max_length=20)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatchannel')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
